### ISSUE TITLE
MongoDB추가

### ISSUE THREAD

**Issue by hyojinbae** [kodevops/food-web#6]

**Comment by hyojinbae** [comment]
@richellin https://github.com/kodevops/food-web 몽고디비 추가했습니다. 우선 저장, 취득되는 샘플코드도 넣어놨으니,  README에 "실행하기" 따라해보시고, 실행되는지 알려주세요

**Comment by richellin** [comment]
@hyojinbae 감사합니다! 한번 해볼게요!
